services:
  evolution:
    image: nginx:alpine
    container_name: evolution
    restart: unless-stopped
    ports:
      - "8081:80"
    env_file:
      - ./.env
    volumes:
      - ./data:/usr/share/nginx/html
      - ../shared/uploads:/usr/share/nginx/html/uploads:ro

networks:
  default:
    name: automation-network
    external: true
